export const GET_BURGER_INGREDIENTS_REQUEST: 'GET_BURGER_INGREDIENT_REQUEST' = 'GET_BURGER_INGREDIENT_REQUEST';
export const GET_BURGER_INGREDIENTS_SUCCESS: 'GET_BURGER_INGREDIENTS_SUCCESS' = 'GET_BURGER_INGREDIENTS_SUCCESS';
export const GET_BURGER_INGREDIENTS_FAILED: 'GET_BURGER_INGREDIENTS_FAILED' = 'GET_BURGER_INGREDIENTS_FAILED';
export const INCREASE_COUNTER: 'INCREASE_COUNTER' = 'INCREASE_COUNTER';
export const DECREASE_COUNTER: 'DECREASE_COUNTER' = 'DECREASE_COUNTER';
export const RESET_COUNTER: 'RESET_COUNTER' = 'RESET_COUNTER';
