export const ORDER_REQUEST: 'ORDER_NUMBER_REQUEST' = 'ORDER_NUMBER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_NUMBER_SUCCESS' = 'ORDER_NUMBER_SUCCESS';
export const ORDER_FAILED: 'ORDER_NUMBER_FAILED' = 'ORDER_NUMBER_FAILED';
export const ORDER_RESET: 'ORDER_RESET' = 'ORDER_RESET';